name: Build Minetest Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:unstable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            g++ \
            make \
            libc6-dev \
            cmake \
            libpng-dev \
            libjpeg-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libsqlite3-dev \
            libogg-dev \
            libvorbis-dev \
            libopenal-dev \
            libcurl4-gnutls-dev \
            libfreetype6-dev \
            zlib1g-dev \
            libgmp-dev \
            libjsoncpp-dev \
            libzstd-dev \
            libluajit-5.1-dev \
            git

      - name: Build Minetest
        run: |
          cd minetest
          cmake .
          make

      - name: Create Debian package
        run: |
          cd minetest
          mkdir -p debian/minetest
          cp -r bin debian/minetest
          dpkg-deb --build debian/minetest

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: minetest-debian-package
          path: minetest/debian/minetest*.deb
          
