name: Build Minetest Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libc6-dev cmake libpng-dev libjpeg-dev libxi-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev libzstd-dev libluajit-5.1-dev git
      
    - name: Clone Minetest repository
      run: git clone --depth 1 --branch stable-5 https://github.com/minetest/minetest.git
      
    - name: Clone Irrlicht repository
      run: git clone --depth 1 https://github.com/minetest/irrlicht.git minetest/lib/irrlichtmt
      
    - name: Checkout specific Irrlicht version
      run: |
        cd minetest/lib/irrlichtmt/
        git fetch --all --tags
        git checkout 1.9.0mt13
      
    - name: Build Minetest
      run: |
        cd minetest
        cmake .
        make
      
    - name: Create Debian package
      run: |
        cd minetest
        mkdir -p debian/minetest
        cp -r bin share debian/minetest
        dpkg-deb --build debian/minetest

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: minetest-debian-package
        path: minetest/debian/minetest*.deb
        
