name: Build Minetest Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            g++ \
            make \
            libc6-dev \
            cmake \
            libpng-dev \
            libjpeg-dev \
            libsdl2-dev \
            libfreetype6-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libopenal-dev \
            libogg-dev \
            libvorbis-dev \
            libcurl4-gnutls-dev \
            libgmp-dev \
            libjsoncpp-dev \
            libzstd-dev \
            libluajit-5.1-dev \
            gettext

      - name: Clone Minetest repository
        run: git clone --depth 1 https://github.com/minetest/minetest.git

      - name: Change to minetest directory
        run: cd minetest

      - name: Build Minetest
        run: |
          cmake . -DRUN_IN_PLACE=TRUE
          make -j$(nproc)

      - name: Create Debian package
        run: |
          mkdir -p debian/minetest
          cp -r bin debian/minetest
          dpkg-deb --build debian/minetest

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: minetest-debian-package
          path: minetest/debian/minetest*.deb
