name: Build Minetest Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone Minetest repository
        run: git clone --depth 1 --branch stable-5 https://github.com/minetest/minetest.git

      - name: Clone Irrlicht repository
        run: git clone --depth 1 --branch 1.9.0mt13 https://github.com/minetest/irrlicht.git minetest/lib/irrlichtmt

      - name: Navigate to Minetest directory
        run: cd minetest

      - name: Run CMake
        run: cmake . -DRUN_IN_PLACE=TRUE

      - name: Build Minetest
        run: make -j$(nproc)

      - name: Create Debian package
        run: |
          mkdir -p debian/minetest
          cp -r bin debian/minetest
          dpkg-deb --build debian/minetest
