name: Build Minetest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ make libc6-dev cmake libpng-dev libjpeg-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev libzstd-dev libluajit-5.1-dev gettext libsdl2-dev

    - name: Clone Minetest
      run: |
        git clone --depth 1 https://github.com/minetest/minetest.git
        cd minetest

    - name: Build Minetest
      run: |
        cmake . -DRUN_IN_PLACE=TRUE
        make -j$(nproc)

    - name: Run Minetest
      run: |
        ./bin/minetest
